authentication:
  userId: admin
  password: 123

spring:
  h2:
    console:
      enabled: true
  server:
    baseUrl : http://localhost    
  security:
    user:
      name : admin
      password: 123
  jpa:
    hibernate :
      ddl-auto : create
    show-sql : true